### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by ShivamJoker** [Xstoudi/pino-pg#153]
I am getting this while using it with esm package
```sh
$ nodemon -r esm -e yaml,js,json index | pino-pg --connectionUrl postgres://xxx:xxx@host.com:5432/easycollab --table test.logs --column log

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/shivam/real-dev/easy-collab-api/node_modules/pino-pg/dist/src/index.js:36:100
    at Generator.next (<anonymous>)
    at resume (/Users/shivam/real-dev/easy-collab-api/node_modules/pino-pg/dist/src/index.js:15:44)
    at fulfill (/Users/shivam/real-dev/easy-collab-api/node_modules/pino-pg/dist/src/index.js:17:31)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

```

**Comment by Xstoudi** [comment]
First, thanks for the report!
I'll be unable to address this until 1st of July. You can submit a PR if you need it sooner.
